"""Generate src/10-rules-pack.js from the real rules_packs/ JSON.

The standalone build has no filesystem, so the pack ships inside the bundle.
Re-run this whenever rules_packs/ changes; never hand-edit the generated file.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PACK_ROOT = HERE.parent / "rules_packs"
OUT = HERE / "src" / "10-rules-pack.js"

FILES = ("pack", "classes", "species", "weapons", "armor", "monsters")


def build() -> str:
    packs: dict[str, dict] = {}
    for pack_dir in sorted(p for p in PACK_ROOT.iterdir() if p.is_dir()):
        data = {}
        for name in FILES:
            path = pack_dir / f"{name}.json"
            if path.is_file():
                data[name] = json.loads(path.read_text(encoding="utf-8"))
        if data:
            packs[pack_dir.name] = data

    body = json.dumps(packs, indent=1, sort_keys=False)
    return (
        "// GENERATED by standalone/embed_rules.py -- do not edit by hand.\n"
        "// Source: rules_packs/*/  (SRD 5.1 content is CC-BY-4.0, see LICENSE)\n"
        "(function (DMAI) {\n"
        "  'use strict';\n"
        f"  DMAI.PACKS = {body};\n"
        "})(window.DMAI = window.DMAI || {});\n"
    )


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
